version: "3"

services:
  
  rtpengine:
    image: fonoster/rtpengine:latest
    build:
      context: .
    network_mode: "host" # At the moment this option only works in Linux
    environment:
      RTPENGINE_PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
      RTPENGINE_PORT_MIN: 10000
      RTPENGINE_PORT_MAX: 20000
      RTPENGINE_LOG_LEVEL: '6'
